# ---------------------------------------------------------------------------
# Rewritten 2026-10-05 after the 2026-09-16 failed apply. NOT yet applied -
# this is the corrected design, unverified end-to-end until a real apply.
#
# AWS side: `hashicorp/aws` has no `aws_interconnect*` resource (confirmed).
# `hashicorp/awscc` - generated directly from the same Cloud Control API
# schema CloudFormation uses - ships `awscc_interconnect_connection`
# (AWS Interconnect went GA in April 2026, CloudFormation got day-1 support,
# awscc inherited it).
#
# Azure side: Multicloud Interconnect is a regular
# `Microsoft.Network/expressRouteCircuits` resource (API 2025-09-01) with
# three differences from a classic provider circuit, which is why the first
# attempt (azurerm circuit, `service_provider_name = "AWS"`, tier Standard)
# ended in Failed/NotProvisioned with a placeholder service_key:
#   1. sku.tier = "MultiCloud" (sku.name = "MultiCloud_MeteredData")
#   2. properties.partnerAccountId = the AWS account that will redeem the key
#   3. the key AWS redeems is properties.activationKey (base64 JSON), NOT
#      serviceKey
# On top of that, the old AWS side asked for 500Mbps while Azure asked for
# 1000 - the activation key is validated against bandwidth, so they must
# match (1Gbps is the only size in the preview).
# `azurerm` 5.8 exposes none of this (tiers stop at Local/Standard/Premium,
# no partnerAccountId/activationKey), hence `azapi` for the circuit only.
# It is a public preview (since 2026-08-26), not allow-listed: the
# aka.ms/MCIForm form is only for requesting extra regions.
# ---------------------------------------------------------------------------

# --- AWS side: Direct Connect Gateway + VPN Gateway + Interconnect ---------
# A DX Gateway is the attach point AWS Interconnect uses on this side. It's
# a free, logical construct (no hourly cost by itself - see README pricing
# table). Associated to a VPN Gateway rather than a Transit Gateway since
# this PoC is a single VPC - no need to pay for a TGW just for this test.

resource "aws_dx_gateway" "poc" {
  name            = "dxgw-aws-azure-interconnect-poc"
  amazon_side_asn = 64512
}

resource "aws_vpn_gateway" "poc" {
  vpc_id = module.aws_vpc.vpc_id

  tags = merge(local.tags, { Name = "vgw-aws-azure-interconnect-poc" })
}

resource "aws_dx_gateway_association" "poc" {
  dx_gateway_id         = aws_dx_gateway.poc.id
  associated_gateway_id = aws_vpn_gateway.poc.id
  allowed_prefixes      = [local.aws_vpc_cidr]
}

# Redeems the Azure circuit's activationKey (see azapi_resource.circuit
# below) - the actual cross-cloud handshake, via the awscc (Cloud Control)
# provider since hashicorp/aws doesn't have this resource yet.
resource "awscc_interconnect_connection" "poc" {
  attach_point = {
    direct_connect_gateway = aws_dx_gateway.poc.id
  }
  bandwidth      = "1Gbps" # must match the Azure circuit - the activation key is validated against it, and 1Gbps is the only preview size
  activation_key = azapi_resource.circuit.output.properties.activationKey
}

# --- Azure side: Multicloud Interconnect circuit + Gateway + Connection ----
# `useast` (not `us-east-1`/`eastus`) is the peering-location spelling Azure
# uses internally for the AWS provider - confirmed 2026-10-05 via
# `az network express-route list-service-providers` (the only offer listed
# is 1Gbps). See the top-of-file comment for why this is an azapi resource
# and not azurerm_express_route_circuit.

resource "azapi_resource" "circuit" {
  type      = "Microsoft.Network/expressRouteCircuits@2025-09-01"
  name      = "erc-aws-azure-interconnect-poc"
  parent_id = azurerm_resource_group.this.id
  location  = var.azure_location

  # azapi 2.13.0 only embeds expressRouteCircuits schemas up to 2025-07-01;
  # the MultiCloud tier / partnerAccountId / activationKey are documented in
  # 2025-09-01 (Get MultiCloud ExpressRouteCircuit example). The body is sent
  # as-is to ARM, so skip the local schema check for this one resource.
  schema_validation_enabled = false

  body = {
    sku = {
      name   = "MultiCloud_MeteredData"
      tier   = "MultiCloud"
      family = "MeteredData"
    }
    properties = {
      serviceProviderProperties = {
        serviceProviderName = "AWS"
        peeringLocation     = "useast"
        bandwidthInMbps     = 1000
      }
      partnerAccountId = data.aws_caller_identity.current.account_id
    }
  }

  tags = local.tags

  # activationKey is generated by Azure; whether it is populated right when
  # the PUT returns or shows up async is unverified - if the first apply
  # reads it back empty, re-read via a data source before the awscc side.
  response_export_values = [
    "properties.activationKey",
    "properties.serviceProviderProvisioningState",
  ]

  timeouts {
    create = "30m"
    delete = "30m"
  }
}

# Azure Multicloud Interconnect's own FAQ: "Do I need an ExpressRoute
# gateway? Yes." - traffic entering the VNet over the interconnect arrives
# through this gateway. `type = "ExpressRoute"` gateways don't take a public
# IP (the provider explicitly rejects one), unlike a Vpn-type gateway.
#
# This is the single most expensive and slowest-to-provision resource in
# this whole PoC (create time 30-60 min per Terraform's own provider notes,
# plus an hourly SKU cost that keeps running until it's destroyed) - see
# README for the cost callout and teardown reminder.

resource "azurerm_virtual_network_gateway" "poc" {
  name                = "ergw-aws-azure-interconnect-poc"
  location            = var.azure_location
  resource_group_name = azurerm_resource_group.this.name
  type                = "ExpressRoute"
  sku                 = "Standard" # cheapest ExpressRoute-capable SKU; $0.19/hour confirmed via the Azure Retail Prices API

  ip_configuration {
    name      = "default"
    subnet_id = azurerm_subnet.gateway.id
  }

  tags = local.tags
}

resource "azurerm_virtual_network_gateway_connection" "poc" {
  name                       = "conn-aws-azure-interconnect-poc"
  location                   = var.azure_location
  resource_group_name        = azurerm_resource_group.this.name
  type                       = "ExpressRoute"
  virtual_network_gateway_id = azurerm_virtual_network_gateway.poc.id
  express_route_circuit_id   = azapi_resource.circuit.id

  tags = local.tags
}
