variable "aws_region" {
  description = "AWS region for this PoC. Must be one of the 4 AWS Interconnect preview regions: us-east-1, us-west-1, ap-southeast-2, eu-central-1."
  type        = string
  default     = "us-east-1"
}

variable "azure_location" {
  description = "Azure region paired with aws_region for Multicloud Interconnect. us-east-1 pairs with eastus (the only valid pairing among the 4 preview regions)."
  type        = string
  default     = "eastus"
}

variable "azure_subscription_id" {
  description = "Azure subscription ID to deploy into."
  type        = string
}

variable "azure_resource_group_name" {
  description = "Resource group for the Azure side of this PoC."
  type        = string
  default     = "rg-aws-azure-interconnect-poc"
}

variable "environment" {
  type    = string
  default = "poc"
}

variable "owner" {
  type    = string
  default = "johan"
}

variable "azure_vm_ssh_public_key" {
  description = "SSH public key for the Azure PoC VM. Required by azurerm_linux_virtual_machine even though real access is via `az vm run-command` (Run Command), not SSH - the NSG never opens port 22."
  type        = string
}

# --- The one unavoidable manual step ---------------------------------------
# Azure Multicloud Interconnect has zero automation surface as of 2026-09-13
# (confirmed: no CLI extension, no ARM/Bicep example, no REST API spec found -
# see CLAUDE.md for the full trail). The ExpressRoute circuit with Port type
# "Azure Multicloud Interconnect" has to be created once by hand in the Azure
# Portal, which is also where you generate the activation key. Everything
# downstream of those two values - redeeming the key on the AWS side,
# connecting the circuit to the VNet gateway on the Azure side - is Terraform.

variable "azure_multicloud_interconnect_circuit_id" {
  description = "Resource ID of the ExpressRoute circuit (Port type = Azure Multicloud Interconnect) created manually in the Azure Portal. Feeds azurerm_virtual_network_gateway_connection - see README's manual step."
  type        = string
}

variable "aws_interconnect_activation_key" {
  description = "Activation key generated by the manual Azure Portal step above, redeemed here by awscc_interconnect_connection to complete the AWS side."
  type        = string
  sensitive   = true
}
